name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "*"
    # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Install graph-cli
        run: yarn global add @graphprotocol/graph-cli
      - name: Codegen
        run: graph codegen
      - name: Build
        run: yarn build
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint

